### ISSUE TITLE
RuntimeWarning: divide by zero encountered

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/Physical_Simulation_Environment#2]
when running main.py the following error showed up on the terminal:
/Users/ggrammel/git/TIP_GNmodel/Develop/Physical_Simulation_Environment/src/gnpy.py:155: RuntimeWarning: divide by zero encountered in double_scalars
  f_lim = np.sqrt(np.power(alpha_lin, 2)/(4*np.power(np.pi, 4)*b2*b2)*(min_FWM_inv-1))/(f1-f)+f
Elapsed: 132.898845911
./main.py:28: RuntimeWarning: divide by zero encountered in log10
  plt.plot(fch_NLI,10*np.log10(nli),'ro',label='GNLI')

**Comment by aleFerrari** [comment]
Bug fixed.
Thanks for the report.
Alessio
